if (ENABLE_TESTS)
    find_package(GTest QUIET)
    if (NOT GTest_FOUND)
        message(WARNING "GTest not found; tests will be disabled for this configure run.")
        set(ENABLE_TESTS OFF CACHE BOOL "Build tests" FORCE)
    endif ()
endif ()
