name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch dependencies
        shell: bash
        run: scripts/install_dependencies.sh

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          ninja

      - name: Test
        run: |
          cd build
          ./tests/test_batch
          ./tests/test_columnar
          ./tests/test_columns
          ./tests/test_csv
          ./tests/test_fileio
          ./tests/test_stream

  sanitizers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch dependencies
        shell: bash
        run: scripts/install_dependencies.sh

      - name: Configure CMake With Sanitizers
        env:
          CC: clang-18
          CXX: clang++-18
        run: |
          mkdir -p build-sanitizers
          cd build-sanitizers
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCOLUMNAR_SANITIZERS=address,undefined ..

      - name: Build With Sanitizers
        run: |
          cd build-sanitizers
          ninja

      - name: Test With Sanitizers
        env:
          ASAN_OPTIONS: detect_leaks=1:strict_string_checks=1:check_initialization_order=1
          UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
        run: |
          cd build-sanitizers
          ctest --output-on-failure
